name = "GWGrids"
uuid = "d33f57a8-936b-4b85-ac63-7cab154bb436"
version = "0.1.0"
authors = ["vcantarella <vcantarella@gmail.com>"]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]

[compat]
Test = "1.11.0"
